kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lime-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: standard-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
